version: 2
jobs:
  compile:
    docker:
      - image: fadlyas/kernel_dockerfile:latest
    steps:
      - checkout
      - run: git clone --quiet -j32 --depth=1 https://github.com/fadlyas07/build-scriptsv2 master
      - run: bash master/rolex-pure.sh
  compiletoo:
    docker:
      - image: fadlyas/kernel_dockerfile:latest
    steps:
      - checkout
      - run: git clone --quiet -j32 --depth=1 https://github.com/fadlyas07/build-scriptsv2 master
      - run: bash master/riva-pure.sh
workflows:
  version: 2
  cooking:
    jobs:
      - compile
      - compiletoo
